repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.13
    hooks:
      # Update the uv lockfile
      - id: uv-lock
        files: pyproject.toml
        always_run: true

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--ignore=E203,E302,W503"]
        language_version: python3.13
        files: ^(agents/|tests/).*\.py$
        always_run: true

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        files: ^(agents/|tests/).*\.py$
        always_run: true

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile=black"]
        language_version: python3.13
        files: ^(agents/|tests/).*\.py$
        always_run: true
