name: Lint and Code Style Check

on:
  pull_request:
    branches:
      - main

jobs:
  flake8:
    name: Run flake8 (Code Quality Check)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install flake8
        run: |
          pip install flake8

      - name: Run flake8
        run: |
          flake8 .

  black:
    name: Run black (Code Formatting Check)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install black
        run: |
          pip install black[jupyter]

      - name: Run black
        run: |
          black --check .

  isort:
    name: Run isort (Import Sorting Check)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install isort
        run: |
          pip install isort

      - name: Run isort
        run: |
          isort --check-only .
